name: Publish NBT4J Core GitHub Action

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/publishing_core.yml"
      - "nbt4j-next-core/src/**/*.java"
      - "nbt4j-next-core/build.gradle.kts"
      - "gradle.properties"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: default

    steps:
      - name: Checkout Git
        uses: actions/checkout@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
            distribution: 'zulu'
            java-version: '25'

      - name: Cmod Gradlew
        run: chmod +x gradlew

      - name: SetENV
        run: ./gradlew nbt4j-next-core:publishMavenJavaPublicationToMavenLocal
        env:
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}
